# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

CI=false

# Mod properties
mod_version = 0.0.1
maven_group = dev.bibbythe.fargsclient
archives_name = fargs-client
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.11
yarn_mappings = 1.21.11+build.1

# Dependencies
architectury_api_version = 19.0.1
fabric_loader_version = 0.19.5
fabric_api_version = 0.141.6+1.21.11
neoforge_version = 21.11.45
yarn_mappings_patch_neoforge_version = 1.21+build.6


fabric_bundle_uuid = 00000000-0000-0000-0000-000000000000
neoforge_bundle_uuid = 00000000-0000-0000-0000-000000000000
common_bundle_uuid = 00000000-0000-0000-0000-000000000000