name: build
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v4.7.0
      - name: Set Version
        run: echo "VERSION=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_ENV
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -Pmod_version=${{steps.version_step.outputs.fullSemVer}}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: $${{vars.SENTRY_PROJECT}}
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: $${{vars.SENTRY_PROJECT}}
        with:
          environment: production
          release: ${{steps.version_step.outputs.fullSemVer}}
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.version_step.outputs.fullSemVer}}',
              sha: context.sha
            })
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{steps.version_step.outputs.fullSemVer}}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            fabric/build/libs/fargs-client-fabric-${{steps.version_step.outputs.fullSemVer}}.jar
            neoforge/build/libs/fargs-client-neoforge-${{steps.version_step.outputs.fullSemVer}}.jar